---
# tasks file for asciinema - Ubuntu OS

- name: Ubuntu OS | Adding repository {{ asciinema_ubuntu_repo }}
  ansible.builtin.apt_repository:
    repo: "{{ asciinema_ubuntu_repo }}"
    state: "{{ asciinema_ubuntu_repo_desired_state }}"
    filename: "{{ asciinema_ubuntu_repo_filename }}"
    codename: "{{ ansible_lsb['codename'] }}"
    update_cache: yes

- name: Ubuntu OS | Installing {{ asciinema_app }}
  ansible.builtin.apt:
    name: "{{ asciinema_app }}"
    state: "{{ asciinema_app_desired_state }}"
    force_apt_get: yes
    update_cache: yes
