---
# tasks file for docker - EL Family

- name: EL Family | Installing {{ asciinema_app }}
  ansible.builtin.yum:
    name: "{{ asciinema_app }}"
    state: "{{ asciinema_app_desired_state }}"
    update_cache: yes
