---
# tasks file for asciinema - Debian Family

- name: Debian Family | Installing {{ asciinema_app }}
  ansible.builtin.apt:
    name: "{{ asciinema_app }}"
    state: "{{ asciinema_app_desired_state }}"
    force_apt_get: yes
    update_cache: yes
