---
# tasks file for asciinema

- name: Import install_debian.yml if OS Family is Debian
  ansible.builtin.import_tasks: install_ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Import install_el.yml if OS Family is EL
  ansible.builtin.import_tasks: install_el.yml
  when: ansible_os_family == "RedHat"
